export { default as FacebookIcon } from './FacebookIcon';
export { default as TwitterIcon } from './TwitterIcon';
export { default as SkypeIcon } from './SkypeIcon';
export { default as InstagramIcon } from './InstagramIcon';
export { default as MapPinIcon } from './MapPinIcon';
export { default as PhoneIcon } from './PhoneIcon';
export { default as MailIcon } from './MailIcon';
export { default as ClockIcon } from './ClockIcon';
export { DEFAULT_ICON_SIZE, type IconProps } from './Icons.types';
